name: Docker Image CI

on:
  push:
    branches: [ main,build-1 ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./Docker-Kubernetes/technical-tests/  --tag my-image-name:$(date +%s)